#! /bin/bash

echo "System Updates:"
sudo dnf update

echo "Flatpak Updates:"
flatpak update

echo "Pip Updates:"
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
